# Generated by Django 5.0.3 on 2024-03-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_send_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='recipient',
            field=models.CharField(max_length=255),
        ),
    ]
