# Generated by Django 5.0.3 on 2024-03-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_emailmessage_sent_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Send_email',
        ),
    ]
