# Generated by Django 5.0.3 on 2024-03-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_send_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='recipient',
        ),
    ]
